eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: assurance
          predicates:
            - Path=/api/v1/assurance/**
          uri: http://localhost:8070
        - id: assurancePolicy
          predicates:
            - Path=/api/v1/assurancePolicy/**
          uri: http://localhost:8090
management:
  tracing:
    sampling:
      probability: 1.0

